### ISSUE TITLE
ansiup CSS missing in Drone 1.0

### ISSUE THREAD

**Issue by jhasse** [drone/drone-ui#251]
This worked in 0.8, but was probably forgotten in the UI rewrite. Currently colors in the build output don't show up, since the CSS for them is missing. I've came up with the missing colors and tried to make them look good on the new background color:

```css
.ansi-black-fg { color: #5b5b5b; }
.ansi-red-fg { color: #e23131; }
.ansi-green-fg { color: #4dca7e; }
.ansi-yellow-fg { color: #c7b441; }
.ansi-blue-fg { color: #2ba3d0; }
.ansi-magenta-fg { color: #e948e9; }
.ansi-cyan-fg { color: #4eeeee; }
.ansi-black-bg { background-color: #404040; }
.ansi-red-bg { background-color: #ec3c3c; }
.ansi-green-bg { background-color: #76c84c; }
.ansi-yellow-bg { background-color: #e8b73b; }
.ansi-blue-bg { background-color: #3a5ad0; }
.ansi-magenta-bg { background-color: #c440b6; }
.ansi-cyan-bg { background-color: #32d2d9; }
.ansi-white-bg { background-color: #aeaeae; }
```

before:
![before](https://user-images.githubusercontent.com/80071/51248541-b8ec7500-1990-11e9-8565-d17bc4a5d992.png)

after:
![ansiup](https://user-images.githubusercontent.com/80071/51248450-77f46080-1990-11e9-815b-43b338cae864.png)

Besides the CSS no changes are needed.
