### ISSUE TITLE
Show skipped step as Skipped, and not as Success

### ISSUE THREAD

**Issue by Weasy666** [drone/drone-ui#345]
Currently a step that is skipped because of a trigger, like this:
```yaml
trigger:
    ref:
      include:
      - refs/heads/master
      - refs/pull/*/head
      exclude:
      - refs/heads/*
```
Is still shown as success in the UI, see below:
![grafik](https://user-images.githubusercontent.com/11967542/98244413-b137ff00-1f6f-11eb-884f-8a65c1db4b65.png)

I as a user would expect that the skipped step is also displayed as skipped and not as succeded, like here:
![grafik](https://user-images.githubusercontent.com/11967542/98244982-90bc7480-1f70-11eb-8cf8-65deefce9f0e.png)
