### ISSUE TITLE
How to manually exec special name pipeline

### ISSUE THREAD

**Issue by LGinC** [drone/drone-ui#384]
![image](https://user-images.githubusercontent.com/15363011/133715104-960cd4bf-59ab-416c-8512-4fe0e05e1f51.png)
I want to add a new build to exec special pipeline that name is 'FileServcie'

content of .drone.yml
```yaml
kind: pipeline
type: docker
name: FileService

clone:
  depth: 1

steps:
- name: publish FileService
  image: mcr.microsoft.com/dotnet/sdk:5.0-alpine
  pull: if-not-exists
  commands:
  - cd services/FileService.Host
  - dotnet restore
  - dotnet publish --no-restore -c Release -o app --no-restore
trigger:
  ref:
    include:
    - refs/tags/FileService
```

how to do it?
what the key value pairs should I type?
